# Use the official PHP image as the base image
FROM php:8.0-apache

# Set working directory
WORKDIR /var/www/html

# Copy the application code to the container
COPY . /var/www/html/

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
        libzip-dev \
        unzip \
        git && \
    docker-php-ext-install zip pdo_mysql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set up Apache
RUN a2enmod rewrite && \
    chown -R www-data:www-data /var/www/html

# Set environment variables
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_ERROR_LOG_FILE /var/log/apache2/error.log

# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
